site_name: PiCymru
copyright: PiCymru 2015 - 2016
theme: readthedocs
extra_css: ['extra.css']
pages:
  - 'Home': 'index.md'
  - 'Device Lab':
      - 'About': 'devicelab/index.md'
      - 'Directions': 'devicelab/directions.md'
      - 'Fees': 'devicelab/fees.md'
  - 'Online Lab':
      - 'Setup': 'onlinelab/setup.md'
      - 'Connecting': 'onlinelab/connecting.md'
      - 'Using': 'onlinelab/using.md'
      - 'Frequently Asked Questions': 'onlinelab/faq.md' 