site_name: PiCymru
copyright: PiCymru 2015 - 2016
theme: readthedocs
extra_css: ['extra.css']
pages:
  - 'Home': 'index.md'
  - 'Code Hosting (codedin.wales)':
      - 'About': 'codedin/index.md'
  - 'Device Lab':
      - 'About': 'devicelab/index.md'
      - 'Directions': 'devicelab/directions.md'
  - 'Services':
      - 'Minecraft': 'services/minecraft.md'