site_name: PiCymru
copyright: '&copy; PiCymru 2017'
extra_css: ['extra.css']
pages:
  - 'Home': 'index.md'
  - 'Device Lab':
      - 'Home': 'devicelab/index.md'
      - 'Locations':
        - 'Swansea': 'devicelab/swansea/index.md'
  - 'Services':
      - 'Minecraft': 'services/minecraft.md'
      - 'codedin.wales':
        - 'Terms of Service': 'codedin/terms.md'
        - 'DMCA': 'codedin/dmca.md'
      - 'hostedin.wales':
        - 'Terms of Service': 'hostedin/terms.md'
        - 'DMCA': 'hostedin/dmca.md'